spring.application.name=MechanicApp

spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.auto-commit=false
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


#server.servlet.context-path =/api/vi

# Oauth2 for google
spring.security.oauth2.client.registration.google.client-id =${SPRING_SECURITY_OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret =${SPRING_SECURITY_OAUTH2_CLIENT_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB


server.base-url=${BASE_URL:http://localhost:8080}
# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.jpa.hibernate.ddl-auto=update

verifyway.api.url=https://api.verifyway.com/api/v1/
verifyway.api.key=1972$asphpBaFj9OZdoGV9RvDQOMAG6JgLtFrLIE0


/this is for google storage to tell which type of bucket we use 
gcp.bucket.name=mechanic-app-images-bucket-1

#REDIS CONFIGURATION :
# Redis Cloud Configuration
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}

#this is for payment integration key public and secret

swich.client-id=9d7265c85fac47d0919b48bda01bdfda
swich.secret-key=4DD37412A846B7D8
swich.pwa-url=https://sandbox-payin-pwa.swichnow.com/

swich.payment.url=https://sandbox-payin-pwa.swichnow.com

#firebase private key
firebase.service-account-json=${FIREBASE_SERVICE_ACCOUNT_JSON:}



